services:
  - type: web
    name: motion2music-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000
    pythonVersion: 3.10
